### ISSUE TITLE
Replace ReviewTable placeholder page with one that includes Review Table

### ISSUE THREAD

**Issue by crdgdr** [ucsb-cs156-f22/team03-f22-6pm-2#21]

**Comment by christianvanstralen** [comment]
# Acceptance Criteria
- [x] When going to `List Menu Item Reviews` instead of the placeholder page, the `MenuItemReviewTable` is displayed
- [x] MenuItemReview items are properly displayed on the `MenuItemReviewTable`
- [x] Passes `npm run coverage` and `npx stryker run` tests
- [x] Passes all GitHub tests
